// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'fantsymaker-hk',
    appId: '1:311090574022:web:c30f34e2faaedf10a19dc7',
    storageBucket: 'fantsymaker-hk.appspot.com',
    apiKey: 'AIzaSyCyC6sF4-1DaAwbOethROWOCRqIagiW_4w',
    authDomain: 'fantsymaker-hk.firebaseapp.com',
    messagingSenderId: '311090574022',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
};
